### ISSUE TITLE
Are these fonts the latest versions of the fonts ?

### ISSUE THREAD

**Issue by astrolemonade** [posteroffonts/sanfran#1]

**Comment by KafuChinoDesu** [comment]
I think it is somewhat old version of macOS. It doesn't contain Apple's modern Korean font, Apple SD Gothic Neo.

**Comment by posteroffonts** [comment]
I try to update them to the latest version of macOS when I remember, usually within a month of new releases. The commit message is the OS version.

**Comment by shivangswain** [comment]
Thanks a ton for these fonts btw. Me and many others, who use them on non-Apple platforms, really appreciate your effort!
